FROM python:3.11-slim
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get update
RUN apt-get install python-is-python3 python3-dev lsb-release -y
RUN apt-get install libpq-dev gcc -y
RUN apt-get clean all
