version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f docker/bot/Dockerfile .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - task_definition_name=$(aws ecs describe-services --services redbull-daemon --cluster redbull | jq -r ".services[].taskDefinition")
      - container_name=$(aws ecs describe-task-definition --task-definition $task_definition_name | jq -r '.taskDefinition.containerDefinitions[].name')
      - printf '[{"name":"%s","imageUri":"%s:%s"}]' "$container_name" "$REPOSITORY_URI" "$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - "**/*"
  name: BuildArtifact
