name: Test docker

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  PG_DB_CONNECTION: ${{secrets.PG_DB_CONNECTION}}
  PG_DB_NAME: ${{secrets.PG_DB_NAME}}
  PG_DB_PORT: ${{secrets.PG_DB_PORT}}
  PG_PASSWORD: ${{secrets.PG_PASSWORD}}
  PG_USER: ${{secrets.PG_USER}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  run-in-docker:
    runs-on: ubuntu-20.04
    container: vazome/redbull-tracker-ge:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create samples
        run: |
          touch export_2023.json export_2024.json
      - name: Upload export file
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: ./export*.json
          overwrite: true

  run-in-actions:
    needs: run-in-docker
    runs-on: ubuntu-20.04
    steps:
      - name: Download export file
        uses: actions/download-artifact@v4
        with:
          name: export
      - name: List Samples
        run: |
            ls
         