name: Run Red Bull Price Grabber

on:
  schedule:
    - cron: '0 7 * * *' # Runs at 07:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python script
      run: python ./run.py
    - name: Commit report
      run: |
        git config --global user.name 'vazome'
        git config --global user.email 'vazome@users.noreply.github.com'
        git add ./export/*
        git commit -am "Adding more price reports to export"
        git push
