name: Zip Lambda Badge code

on:
  push:
    paths:
      - '.aws_lambda/**'
      - '.**/zip_lambda_code.yml'

permissions:
    id-token: write # JWT
    contents: read  # actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Zip Lambda code
          run: |
            zip -r lambda.zip .
          working-directory: ${{github.workspace}}/.aws_lambda

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{secrets.AWS_OIDC_ROLE_ARN}}
            role-session-name: export-aws-lambda-code
            aws-region: ${{secrets.AWS_REGION}}

        - name:  Copy lambda zip to s3
          run: |
            aws s3api put-object --bucket ${{secrets.AWS_BUCKET_NAME}} --key lambda.zip --body lambda.zip --checksum-algorithm sha256
          working-directory: ${{github.workspace}}/.aws_lambda
